# Generated by Django 3.1.4 on 2020-12-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('ingred1', models.CharField(max_length=100)),
                ('amt1', models.CharField(max_length=10)),
                ('unit1', models.CharField(max_length=20)),
                ('ingred2', models.CharField(max_length=100)),
                ('amt2', models.CharField(max_length=10)),
                ('unit2', models.CharField(max_length=20)),
                ('ingred3', models.CharField(max_length=100)),
                ('amt3', models.CharField(max_length=10)),
                ('unit3', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=5)),
                ('tags', models.CharField(max_length=200)),
                ('instructions', models.CharField(max_length=5000)),
            ],
        ),
    ]
