# Generated by Django 3.1.4 on 2020-12-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='amt10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt11',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt12',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt13',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt14',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt15',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt16',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt17',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt18',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt19',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt20',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt4',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt5',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt6',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt7',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt8',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='amt9',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(default='dinner', max_length=50),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred16',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingred9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes10',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes11',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes12',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes13',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes14',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes15',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes16',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes17',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes18',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes19',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes20',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes6',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes7',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes8',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='notes9',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit10',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit11',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit12',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit13',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit14',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit15',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit16',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit17',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit18',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit19',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit20',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit4',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit5',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit6',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit7',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit8',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit9',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
