# Generated by Django 3.1.4 on 2020-12-19 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
    ]
