# Generated by Django 3.1.4 on 2020-12-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0002_remove_ingredient_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, null=True, to='recipe_match.Ingredient'),
        ),
    ]
