# Generated by Django 3.1.4 on 2020-12-16 22:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0004_auto_20201215_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
