# Generated by Django 3.1.4 on 2021-01-07 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0009_auto_20210107_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='g_per_fl_oz',
        ),
    ]
