# Generated by Django 3.1.4 on 2021-01-07 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0010_remove_food_g_per_fl_oz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='calories',
            new_name='calories_in_100g',
        ),
    ]
