# Generated by Django 3.1.4 on 2021-01-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0013_auto_20210107_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='calcium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='cholesterol',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='dietary_fiber',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='fat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='iron',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='magnesium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='phosphorus',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='potassium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='protein',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='saturated_fat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='sodium',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_carbohydrate',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='total_sugars',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='trans_fat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_a',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_b',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_c',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_d',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_e',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='vit_k',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='food',
            name='zinc',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
