# Generated by Django 3.1.4 on 2021-01-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0014_auto_20210107_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shopping_list_unit',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='food',
            name='g_per_c',
            field=models.PositiveSmallIntegerField(default=160),
        ),
        migrations.AlterField(
            model_name='food',
            name='g_per_oz',
            field=models.PositiveSmallIntegerField(default=28),
        ),
    ]
