# Generated by Django 3.1.4 on 2021-01-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0019_food_nutrition_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='g_per_breast',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='g_per_clove',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='g_per_head',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='g_per_stalk',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
