# Generated by Django 3.1.4 on 2021-01-11 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0020_auto_20210110_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='g_per_no_unit',
            new_name='g_per_whole',
        ),
    ]
