# Generated by Django 3.1.4 on 2021-01-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0021_auto_20210110_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='g_per_slice',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
