# Generated by Django 3.1.4 on 2021-01-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_match', '0022_food_g_per_slice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
